spring: 
  datasource:
    url: jdbc:mysql://remotemysql.com/Qiyd5u1gIr
    username: Qiyd5u1gIr
    password: dWIiAln078
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
server:
  port: 9091